
///! This file was generated by tooling/gen. Edit the source data and run
///! that generator instead of hand-editing this file.

const LENGTH: usize = 10;

pub const TYPOS: [&str; LENGTH] = [
    "Can;t",
    "can;t",
    "Don;t",
    "don;t",
    "Preferrable",
    "preferrable",
    "Repetion",
    "repetion",
    "Won;t",
    "won;t",
];

pub const FIXES: [&str; LENGTH] = [
    "Can't",
    "can't",
    "Don't",
    "don't",
    "Preferable",
    "preferable",
    "Repetition",
    "repetition",
    "Won't",
    "won't",
];
