
///! This file was generated by tooling/gen. Edit the source data and run
///! that generator instead of hand-editing this file.

const LENGTH: usize = 3;

pub const TYPOS: [&str; LENGTH] = [
    "don;t",
    "won;t",
    "can;t",
];

pub const FIXES: [&str; LENGTH] = [
    "don't",
    "won't",
    "can't",
];
